name: Publish to npm
on:
  push:
    branches:
      - master
    workflow_dispatch:
  jobs:
    publish-to-npm:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
        - run: npm ci
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secres.NPM_TOKEN }}

            
